name: Build, Scan & Push Docker Image on Release

on:
  release:
    types: [published]
  schedule:
    - cron: "*/5 * * * *"  # toutes les 5 minutes
  workflow_dispatch:       # permet de lancer manuellement aussi
        
jobs:
  call-central:
    uses: veka-server/github-actions-templates/.github/workflows/docker-build.yml@main
    secrets:
      GHCR_PAT: ${{ secrets.GHCR_PAT }}
