name: Replicate GHCR_PAT and Copy Workflow

on:
  workflow_dispatch:
    inputs:
      target_repo:
        description: 'Nom du dépôt cible (ex: mon-app)'
        required: true
        default: 'mon-app'

jobs:
  replicate-and-copy:
    runs-on: ubuntu-latest
    steps:
      - name: Set variables
        run: |
          echo "TARGET_REPO=${{ github.event.inputs.target_repo }}" >> $GITHUB_ENV
          echo "SOURCE_REPO=${{ github.repository }}" >> $GITHUB_ENV

      # 1️⃣ Récupérer la valeur du secret GHCR_PAT depuis le dépôt central
      - name: Get GHCR_PAT value
        id: get_secret
        run: |
          SECRET_VALUE=$(gh secret view GHCR_PAT --repo $SOURCE_REPO --json value -q .value)
          echo "SECRET_VALUE=$SECRET_VALUE" >> $GITHUB_ENV

      # 2️⃣ Ajouter le secret au dépôt cible
      - name: Set GHCR_PAT in target repo
        run: |
          gh secret set GHCR_PAT --repo $TARGET_REPO --body "$SECRET_VALUE"

      # 3️⃣ Copier le fichier templates/build.yml depuis le dépôt central
      - name: Copy template workflow to target repo
        run: |
          # Récupérer le fichier depuis le dépôt source
          FILE_CONTENT=$(gh api repos/$SOURCE_REPO/contents/templates/build.yml \
                         -q .content | base64 --decode)

          # Encoder en base64 pour l'API
          CONTENT_BASE64=$(echo "$FILE_CONTENT" | base64 -w 0)

          # Créer le fichier dans le dépôt cible via l'API
          gh api -X PUT \
            -H "Accept: application/vnd.github+json" \
            /repos/$TARGET_REPO/contents/.github/workflows/use-central.yml \
            -f message="Add workflow to call central build template" \
            -f content="$CONTENT_BASE64"
