name: Replicate GHCR_PAT and Copy Workflow

on:
  workflow_dispatch:
    inputs:
      target_repo:
        description: 'Nom du dépôt cible (ex: mon-app)'
        required: true
      ghcr_pat:
        description: 'Valeur du GHCR_PAT à créer dans le dépôt cible'
        required: true

jobs:
  replicate-and-copy:
    runs-on: ubuntu-latest
    steps:

      # 1️⃣ Installer les dépendances Python
      - name: Setup Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pynacl requests

      # 2️⃣ Créer le secret GHCR_PAT dans le dépôt cible
      - name: Create GHCR_PAT secret in target repo
        env:
          ADMIN_PAT: ${{ secrets.MASTER_PAT }}
          TARGET_REPO: ${{ github.event.inputs.target_repo }}
          SECRET_VALUE: ${{ github.event.inputs.ghcr_pat }}
          SOURCE_USER: ${{ github.repository_owner }}
        run: |
          python - <<'PYTHON'
          import os, requests, json, base64
          import nacl.encoding, nacl.public

          admin_pat = os.environ["ADMIN_PAT"]
          repo = os.environ["TARGET_REPO"]
          secret_value = os.environ["SECRET_VALUE"]
          source_user = os.environ["SOURCE_USER"]

          # 1️⃣ Récupérer la clé publique du dépôt cible
          url = f"https://api.github.com/repos/{source_user}/{repo}/actions/secrets/public-key"
          headers = {"Authorization": f"token {admin_pat}", "Accept": "application/vnd.github+json"}
          r = requests.get(url, headers=headers)
          r.raise_for_status()
          pubkey = r.json()
          key_id = pubkey["key_id"]
          key = pubkey["key"]

          # 2️⃣ Chiffrer le secret
          public_key = nacl.public.PublicKey(key.encode("utf-8"), encoder=nacl.encoding.Base64Encoder)
          sealed_box = nacl.public.SealedBox(public_key)
          encrypted = sealed_box.encrypt(secret_value.encode("utf-8"))
          encrypted_value = base64.b64encode(encrypted).decode("utf-8")

          # 3️⃣ Créer le secret via API
          put_url = f"https://api.github.com/repos/{source_user}/{repo}/actions/secrets/GHCR_PAT"
          data = {"encrypted_value": encrypted_value, "key_id": key_id}
          r = requests.put(put_url, headers=headers, data=json.dumps(data))
          r.raise_for_status()
          print(f"Secret GHCR_PAT créé dans {repo} !")
          PYTHON

      # 3️⃣ Copier le workflow template depuis le dépôt central
      - name: Copy template workflow to target repo
        env:
          GH_TOKEN: ${{ secrets.MASTER_PAT }}   # Obligatoire pour gh CLI
          TARGET_REPO: ${{ github.event.inputs.target_repo }}
          SOURCE_REPO: ${{ github.repository }}
        run: |
          # Récupérer le contenu du template
          FILE_CONTENT=$(gh api repos/$SOURCE_REPO/contents/templates/build.yml \
                         -q .content | base64 --decode)

          # Re-encoder pour GitHub API
          CONTENT_BASE64=$(echo "$FILE_CONTENT" | base64 -w 0)

          # Vérifier si le fichier existe déjà et récupérer le sha
          SHA=$(gh api repos/$SOURCE_REPO/contents/.github/workflows/use-central.yml \
                -q .sha 2>/dev/null || echo "")

          if [ -n "$SHA" ]; then
            # Mettre à jour le fichier existant
            gh api -X PUT \
              /repos/${{ github.repository_owner }}/$TARGET_REPO/contents/.github/workflows/use-central.yml \
              -f message="Update workflow to call central build template" \
              -f content="$CONTENT_BASE64" \
              -f sha="$SHA"
          else
            # Créer le fichier si il n'existe pas
            gh api -X PUT \
              /repos/${{ github.repository_owner }}/$TARGET_REPO/contents/.github/workflows/use-central.yml \
              -f message="Add workflow to call central build template" \
              -f content="$CONTENT_BASE64"
          fi
