name: Replicate GHCR_PAT and Copy Workflow

on:
  workflow_dispatch:
    inputs:
      target_repo:
        description: 'Nom du dépôt cible (ex: mon-app)'
        required: true
        default: 'mon-app'
      ghcr_pat:
        description: 'Valeur du GHCR_PAT à créer dans le dépôt cible'
        required: true

jobs:
  replicate-and-copy:
    runs-on: ubuntu-latest
    steps:
      - name: Set variables
        run: |
          echo "TARGET_REPO=${{ github.event.inputs.target_repo }}" >> $GITHUB_ENV
          echo "SOURCE_REPO=${{ github.repository }}" >> $GITHUB_ENV
          echo "GHCR_PAT_VALUE=${{ github.event.inputs.ghcr_pat }}" >> $GITHUB_ENV

      # 1️⃣ Créer le secret GHCR_PAT dans le dépôt cible en utilisant MASTER_PAT
      - name: Create GHCR_PAT in target repo
        env:
          ADMIN_PAT: ${{ secrets.MASTER_PAT }}
          REPO: ${{ env.TARGET_REPO }}
          SECRET_VALUE: ${{ env.GHCR_PAT_VALUE }}
        run: |
          # Récupérer la clé publique du dépôt cible pour chiffrer le secret
          PUB_KEY_JSON=$(curl -s -H "Authorization: token $ADMIN_PAT" \
            -H "Accept: application/vnd.github+json" \
            https://api.github.com/repos/tonuser/$REPO/actions/secrets/public-key)

          KEY_ID=$(echo "$PUB_KEY_JSON" | jq -r .key_id)
          KEY=$(echo "$PUB_KEY_JSON" | jq -r .key)

          # Chiffrer le secret avec libsodium
          ENCRYPTED_VALUE=$(echo -n "$SECRET_VALUE" | \
            openssl base64 -A | \
            base64 --decode | \
            sodium-native-encrypt --key $KEY) # Ici il faudra utiliser la méthode de chiffrage libsodium en bash/python

          # Créer le secret dans le dépôt cible
          curl -X PUT \
            -H "Authorization: token $ADMIN_PAT" \
            -H "Accept: application/vnd.github+json" \
            https://api.github.com/repos/tonuser/$REPO/actions/secrets/GHCR_PAT \
            -d "{\"encrypted_value\":\"$ENCRYPTED_VALUE\",\"key_id\":\"$KEY_ID\"}"
      
      # 2️⃣ Copier le fichier templates/build.yml depuis le dépôt central
      - name: Copy template workflow to target repo
        run: |
          FILE_CONTENT=$(gh api repos/$SOURCE_REPO/contents/templates/build.yml \
                         -q .content | base64 --decode)

          CONTENT_BASE64=$(echo "$FILE_CONTENT" | base64 -w 0)

          gh api -X PUT \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: token ${{ secrets.MASTER_PAT }}" \
            /repos/$TARGET_REPO/contents/.github/workflows/use-central.yml \
            -f message="Add workflow to call central build template" \
            -f content="$CONTENT_BASE64"
