name: Build, Scan & Push Docker Image Reusable

on:
  workflow_call:
    secrets:
      GHCR_PAT:
        required: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout du repo (sans fetch-depth pour accéder à tous les tags)
      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          fetch-depth: 0  # important pour récupérer tous les tags

      # 2️⃣ Log in au registre GitHub Container Registry
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}

      # 3️⃣ Définir et checkout le bon tag si schedule
      - name: Set image tags and checkout tag
        run: |
          if [ "${{ github.event_name }}" = "schedule" ]; then
            echo "📅 Build programmé détecté"
            TAG=$(git tag | sort -V | tail -n1)
            echo "Dernier tag trouvé: $TAG"
            git checkout "tags/$TAG"
          else
            echo "🚀 Build depuis un événement Release"
            TAG=${GITHUB_REF##*/}
          fi

          REPO_NAME=${GITHUB_REPOSITORY##*/}
          IMAGE="ghcr.io/${{ github.repository_owner }}/$REPO_NAME:$TAG"

          echo "IMAGE=$IMAGE" >> $GITHUB_ENV
          echo "TAG=$TAG" >> $GITHUB_ENV
          echo "REPO_NAME=$REPO_NAME" >> $GITHUB_ENV

      # 4️⃣ Build de l'image Docker (no cache)
      - name: Build Docker image
        run: docker build --no-cache -t $IMAGE .

      # 5️⃣ Scan de l'image avec Trivy
      - name: Scan image with Trivy
        uses: aquasecurity/trivy-action@0.33.1
        with:
          image-ref: ${{ env.IMAGE }}
          format: table
          exit-code: 1
          severity: HIGH,CRITICAL
          vuln-type: os,library
          ignore-unfixed: false
          timeout: 5m

      # 6️⃣ Push de l'image
      - name: Push Docker image
        run: docker push $IMAGE

      # 7️⃣ Push du tag 'latest' seulement si ce n’est pas un run manuel
      - name: Push 'latest' tag (skip if manual)
        if: github.event_name == 'schedule' || github.event_name == 'release'
        run: |
          docker tag $IMAGE ghcr.io/${{ github.repository_owner }}/$REPO_NAME:latest
          docker push ghcr.io/${{ github.repository_owner }}/$REPO_NAME:latest
