name: Build, Scan & Push Docker Image Reusable

on:
  workflow_call:
    secrets:
      GHCR_PAT:
        required: true
      DISCORD_WEBHOOK_URL:
        required: true
    inputs:
      skip_trivy:
        description: "Skip Trivy scan"
        required: false
        default: 'false'
        type: string

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout du repo (sans fetch-depth pour accéder à tous les tags)
      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      # 2️⃣ Log in au registre GitHub Container Registry
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}

      # 3️⃣ Définir et checkout le bon tag si schedule
      - name: Set image tags and checkout tag
        run: |
          if [ "${{ github.event_name }}" = "schedule" ]; then
            echo "📅 Build programmé détecté"
            TAG=$(git tag | sort -V | tail -n1)

            if [ -z "$TAG" ]; then
              echo "⚠️ Aucun tag trouvé — arrêt du workflow sans erreur."
              echo "no_tag_found=true" >> $GITHUB_ENV
              exit 78  # ✅ Arrêt neutre, pas d’erreur
            fi
            
            echo "Dernier tag trouvé: $TAG"
            git checkout "tags/$TAG"
          else
            echo "🚀 Build depuis un événement Release"
            TAG=${GITHUB_REF##*/}
          fi

          REPO_NAME=${GITHUB_REPOSITORY##*/}
          IMAGE="ghcr.io/${{ github.repository_owner }}/$REPO_NAME:$TAG"

          echo "IMAGE=$IMAGE" >> $GITHUB_ENV
          echo "TAG=$TAG" >> $GITHUB_ENV
          echo "REPO_NAME=$REPO_NAME" >> $GITHUB_ENV

      # 4️⃣ Build de l'image Docker (no cache)
      - name: Build Docker image
        run: docker build --no-cache -t $IMAGE .

      # 5️⃣ Scan de l'image avec Trivy (ne stoppe plus le workflow)
      - name: Scan image with Trivy
        if: ${{ inputs.skip_trivy != 'true' }}
        id: trivy
        continue-on-error: true
        uses: aquasecurity/trivy-action@0.33.1
        with:
          image-ref: ${{ env.IMAGE }}
          format: table
          exit-code: 1
          severity: HIGH,CRITICAL
          vuln-type: os,library
          ignore-unfixed: false
          timeout: 5m

      # 5️⃣ bis — Envoi Discord si le scan échoue
      - name: Send Discord alert if vulnerabilities found
        if: steps.trivy.outcome == 'failure'
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
        run: |
          echo "⚠️ Vulnérabilités détectées, envoi d'une alerte Discord..."
          curl -H "Content-Type: application/json" \
               -X POST \
               -d "{\"username\": \"Trivy Alert\", \"content\": \"🚨 Vulnérabilités détectées dans l'image **${{ env.IMAGE }}** lors du build GitHub Actions !\n🔗 [Voir le run GitHub Actions](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})\"}" \
               "$DISCORD_WEBHOOK_URL"

      # 6️⃣ Push de l'image
      - name: Push Docker image
        run: docker push $IMAGE

      # 7️⃣ Push du tag 'latest' seulement si ce n’est pas un run manuel
      - name: Push 'latest' tag (skip if manual)
        if: github.event_name == 'schedule' || github.event_name == 'release'
        run: |
          docker tag $IMAGE ghcr.io/${{ github.repository_owner }}/$REPO_NAME:latest
          docker push ghcr.io/${{ github.repository_owner }}/$REPO_NAME:latest
